export interface Link {
  id: string;
  title: string;
  url: string;
  abstract: string;
  gradient: string;
  cardColor: string;
  requiresAuth?: boolean;
}

// Fixed dark-tint palette for full-card backgrounds. Reused across cards by
// design (see docs/superpowers/specs/2026-08-20-homepage-design.md) - same
// card always gets the same shade since it's assigned here, not derived.
export const CARD_COLORS = {
  indigo: 'linear-gradient(160deg, #1e2a4a, #2d1b4e)',
  slate: 'linear-gradient(160deg, #1f2937, #111827)',
  stone: 'linear-gradient(160deg, #374151, #24262b)',
  ember: 'linear-gradient(160deg, #4a2413, #4a1530)',
  forest: 'linear-gradient(160deg, #0b3d2e, #064e3b)',
  onyx: 'linear-gradient(160deg, #18181b, #0a0a0a)',
  rustBlue: 'linear-gradient(160deg, #4a2a10, #1e2a52)',
  teal: 'linear-gradient(160deg, #0b3d3a, #0c4a52)',
} as const;

export const links: Link[] = [
  {
    id: 'linkedin',
    title: 'LinkedIn',
    url: 'https://www.linkedin.com/in/klaushofrichter',
    abstract: 'Professional profile, career history, and updates.',
    gradient: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
    cardColor: CARD_COLORS.indigo,
  },
  {
    id: 'github',
    title: 'GitHub',
    url: 'https://github.com/klaushofrichter',
    abstract: 'Open-source projects, code, and experiments.',
    gradient: 'linear-gradient(135deg, #1f2937, #374151)',
    cardColor: CARD_COLORS.slate,
  },
  {
    id: 'portfolio2017',
    title: 'Portfolio 2017',
    url: 'https://klaushofrichter.wordpress.com',
    abstract: 'An earlier portfolio and blog archive.',
    gradient: 'linear-gradient(135deg, #6b7280, #9ca3af)',
    cardColor: CARD_COLORS.stone,
  },
  {
    id: 'instagram',
    title: 'Instagram',
    url: 'https://www.instagram.com/klaushofrichter',
    abstract: 'Photos and moments, shared casually.',
    gradient: 'linear-gradient(135deg, #f97316, #ec4899)',
    cardColor: CARD_COLORS.ember,
  },
  {
    id: 'instagetter',
    title: 'instagetter',
    url: 'https://insta.skylar.technology',
    abstract: 'A self-hosted gallery of my Instagram photos, served from S3.',
    gradient: 'linear-gradient(135deg, #c13584, #833ab4)',
    cardColor: CARD_COLORS.teal,
  },
  {
    id: 'threepuppies',
    title: 'Three Puppies',
    url: 'https://three-pups.mystrikingly.com',
    abstract: 'A small site about three very good dogs.',
    gradient: 'linear-gradient(135deg, #059669, #10b981)',
    cardColor: CARD_COLORS.forest,
  },
  {
    id: 'medium',
    title: 'Medium',
    url: 'https://medium.com/@klaushofrichter',
    abstract: 'Articles and longer-form writing.',
    gradient: 'linear-gradient(135deg, #000000, #3a3a3a)',
    cardColor: CARD_COLORS.onyx,
  },
  {
    id: 'skylar',
    title: 'Skylar Technology',
    url: 'https://www.skylar.technology',
    abstract: 'Skylar Technology LLC.',
    gradient: 'linear-gradient(135deg, #ea580c, #2563eb)',
    cardColor: CARD_COLORS.rustBlue,
  },
  {
    id: 'status',
    title: 'Status',
    url: 'https://status.klaushofrichter.net',
    abstract: 'Live uptime and status monitoring for my services.',
    gradient: 'linear-gradient(135deg, #16a34a, #0891b2)',
    cardColor: CARD_COLORS.teal,
    requiresAuth: true,
  },
  {
    id: 'headlamp',
    title: 'Headlamp',
    url: 'https://headlamp.skylar.technology',
    abstract: 'Kubernetes cluster dashboard for the Skylar Technology infrastructure.',
    gradient: 'linear-gradient(135deg, #ea580c, #2563eb)',
    cardColor: CARD_COLORS.rustBlue,
    requiresAuth: true,
  },
  {
    id: 'grafana',
    title: 'Grafana',
    url: 'https://klaushofrichter.grafana.net/d/kl9nd7q/skylar-technology-node-overview',
    abstract: 'Node metrics dashboard for the Skylar Technology cluster.',
    gradient: 'linear-gradient(135deg, #f97316, #eab308)',
    cardColor: CARD_COLORS.ember,
    requiresAuth: true,
  },
  {
    id: 'steps',
    title: 'Steps',
    url: 'https://steps.skylar.technology',
    abstract: 'Personal step count and Claude usage status dashboard.',
    gradient: 'linear-gradient(135deg, #000000, #3a3a3a)',
    cardColor: CARD_COLORS.onyx,
    requiresAuth: true,
  },
  {
    id: 'ghpages',
    title: 'GitHub Pages Apps',
    url: 'https://klaushofrichter.github.io/klaushofrichter',
    abstract: 'A collection of small deployed apps and demos.',
    gradient: 'linear-gradient(135deg, #6b7280, #9ca3af)',
    cardColor: CARD_COLORS.stone,
    requiresAuth: true,
  },
  {
    id: 'homeassistant',
    title: 'Home Assistant',
    url: 'https://ha.skylar.technology',
    abstract: 'Home automation dashboard for lights, climate, and devices.',
    gradient: 'linear-gradient(135deg, #03a9f4, #41bdf5)',
    cardColor: CARD_COLORS.teal,
    requiresAuth: true,
  },
  {
    id: 'slack',
    title: 'Slack',
    url: 'https://klaushofrichter.slack.com',
    abstract: 'Team workspace for messages and notifications.',
    gradient: 'linear-gradient(135deg, #611f69, #36c5f0)',
    cardColor: CARD_COLORS.indigo,
    requiresAuth: true,
  },
  {
    id: 'squarespace',
    title: 'Squarespace Domains',
    url: 'https://account.squarespace.com/domains',
    abstract: 'Domain registrations and renewal status.',
    gradient: 'linear-gradient(135deg, #18181b, #52525b)',
    cardColor: CARD_COLORS.onyx,
    requiresAuth: true,
  },
  {
    id: 'uptimerobot',
    title: 'UptimeRobot',
    url: 'https://dashboard.uptimerobot.com/monitors',
    abstract: 'Uptime monitor list and status dashboard.',
    gradient: 'linear-gradient(135deg, #3ea66d, #2dd4bf)',
    cardColor: CARD_COLORS.forest,
    requiresAuth: true,
  },
  {
    id: 'hostinger',
    title: 'Hostinger',
    url: 'https://hpanel.hostinger.com/vps/1412632/overview',
    abstract: 'VPS hosting control panel and server management.',
    gradient: 'linear-gradient(135deg, #673de6, #9333ea)',
    cardColor: CARD_COLORS.indigo,
    requiresAuth: true,
  },
  {
    id: 'cloudflare',
    title: 'Cloudflare',
    url: 'https://dash.cloudflare.com/2335333b033ad754951a1dac290a3cc5/home',
    abstract: 'DNS, domains, and Workers account dashboard.',
    gradient: 'linear-gradient(135deg, #f38020, #faad3f)',
    cardColor: CARD_COLORS.ember,
    requiresAuth: true,
  },
  {
    id: 'aws',
    title: 'AWS Console',
    url: 'https://console.aws.amazon.com',
    abstract: 'Amazon Web Services console home, cost and usage overview.',
    gradient: 'linear-gradient(135deg, #232f3e, #ff9900)',
    cardColor: CARD_COLORS.slate,
    requiresAuth: true,
  },
  {
    id: 'bulbs',
    title: 'Kauf Bulbs',
    url: 'https://bulbs.skylar.technology',
    abstract: 'Smart bulb control panel for on/off switching across the house.',
    gradient: 'linear-gradient(135deg, #16a34a, #a3e635)',
    cardColor: CARD_COLORS.forest,
    requiresAuth: true,
  },
];
